import { useEffect, useRef, useState } from 'react'

import styles from './TableOfContents.module.scss'
import { makeCn } from '../../utils/makeCn'

const cn = makeCn('TableOfContents', styles)

interface Heading {
  id: string
  text: string
  level: 2 | 3
}

interface TableOfContentsProps {
  content: string
}

const TableOfContents = ({ content }: TableOfContentsProps) => {
  const [headings, setHeadings] = useState<Heading[]>([])
  const [activeId, setActiveId] = useState('')
  const visibleRef = useRef(new Set<string>())

  useEffect(() => {
    setActiveId('')
    visibleRef.current.clear()
    setHeadings([])

    if (!content) return

    // Read headings from DOM to get exact IDs generated by rehype-slug
    const timer = setTimeout(() => {
      const container = document.querySelector('.markdown')
      if (!container) return

      const found: Heading[] = Array.from(container.querySelectorAll('h2, h3'))
        .map(el => ({
          id: el.id,
          text: el.textContent ?? '',
          level: (el.tagName === 'H2' ? 2 : 3) as 2 | 3,
        }))
        .filter(h => h.id && h.text)

      setHeadings(found)
    }, 0)

    return () => clearTimeout(timer)
  }, [content])

  useEffect(() => {
    if (headings.length === 0) return

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            visibleRef.current.add(entry.target.id)
          } else {
            visibleRef.current.delete(entry.target.id)
          }
        })
        const active = headings.find(h => visibleRef.current.has(h.id))
        if (active) setActiveId(active.id)
      },
      { rootMargin: '-64px 0px -80% 0px', threshold: 0 },
    )

    headings.forEach(({ id }) => {
      const el = document.getElementById(id)
      if (el) observer.observe(el)
    })

    return () => observer.disconnect()
  }, [headings])

  if (headings.length === 0) return null

  const handleClick = (id: string) => {
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  return (
    <nav className={cn()} aria-label="On this page">
      <p className={cn('label')}>On this page</p>
      <ul className={cn('list')}>
        {headings.map(({ id, text, level }) => (
          <li key={id} className={cn('item', { h3: level === 3 })}>
            <button
              type="button"
              className={cn('link', { active: activeId === id })}
              onClick={() => handleClick(id)}
            >
              {text}
            </button>
          </li>
        ))}
      </ul>
    </nav>
  )
}

export default TableOfContents
